[Basic]
run_name = 'LSCodecSML'
run_folder = './runs/lscodec'

[Data]
data_root = './processed/MSL'
data_range = [224, 320]
data_alpha = 0.1
data_overlap = 0.4
data_scale = 'large'
num_work = 0

[Train]
lr = 1e-4
weight_decay = 1e-2
warmup_steps = 10
grad_norm = 1.0
batch_size = 16
valid_size = 20
force_rebuild = true

progress = true
enable_schedule = false
max_epoch = 1000
max_iters = 500_000
save_every_iter = 2000
print_every_iter = 200
resume = true

[LSCodec]
n_feat = 55
n_latent = 256
strides = [2, 4, 2]
n_kernel = 5
n_layer = 4
n_lstm = 2
n_cycle = 12
dropout=0.1

[Loss]
lambda_rec = 1.0
lambda_rec_g = 1.0
lambda_rec_l = 1.0
lambda_commit = 10.0
enable_balancer = false